[package]
name = "erjson"
version = "0.1.0"
authors = ["Evance Soumaoro <evanxg852000@gmail.com>"]
edition = "2018"
description = "A simple rust json parser "
repository = "https://github.com/evanxg852000/erjson"
readme = "README.md"
license = "MIT"

[dependencies]
